Repository SOPT-all/35-APPJAM-SERVER-CAKEY, pull requests merged in 2025-01, with the labels that each got.

#3 [SETTING] 멀티모듈 프로젝트 세팅 - #2
  .gitattributes
  .gitignore
  build.gradle
  cakey-api/build.gradle
  cakey-api/src/main/java/com/cakey/CakeyServerApplication.java
  cakey-auth/build.gradle
  cakey-auth/src/main/java/com/cakey/Main.java
  cakey-common/build.gradle
  cakey-common/src/main/java/com/cakey/Main.java
  cakey-domain/build.gradle
  cakey-domain/src/main/java/com/cakey/Main.java
  cakey-external/build.gradle
  cakey-external/src/main/java/com/cakey/Main.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: setting, 성준

#6 [FEAT, SETTING] 패키지 구조 + exception 세팅, 공통 baseResponse 구현 - #4
  cakey-api/src/main/java/com/cakey/common/response/ApiResponseUtil.java
  cakey-api/src/main/java/com/cakey/common/response/BaseResponse.java
  cakey-api/src/main/java/com/cakey/common/response/SuccessCode.java
  cakey-api/src/main/java/com/cakey/controller/.gitkeep
  cakey-api/src/main/java/com/cakey/dto/.gitkeep
  cakey-api/src/main/java/com/cakey/exception/handler/GlobalExceptionHandler.java
  cakey-api/src/main/java/com/cakey/exception/user/.gitkeep
  cakey-api/src/main/java/com/cakey/facade/.gitkeep
  cakey-api/src/main/java/com/cakey/user/controller/.gitkeep
  cakey-api/src/main/java/com/cakey/user/dto/.gitkeep
  cakey-api/src/main/java/com/cakey/user/exception/UserApiException.java
  cakey-api/src/main/java/com/cakey/user/exception/UserErrorCode.java
  cakey-api/src/main/java/com/cakey/user/facade/.gitkeep
  cakey-common/src/main/java/com/cakey/ApiCode.java
  cakey-common/src/main/java/com/cakey/Main.java
  cakey-common/src/main/java/com/cakey/exception/CakeyException.java
  cakey-common/src/main/java/com/cakey/exception/ErrorCode.java
  cakey-common/src/main/java/com/cakey/exception/UserBaseException.java
  cakey-domain/build.gradle
  cakey-domain/src/main/java/com/cakey/Main.java
  cakey-domain/src/main/java/com/cakey/common/BaseTimeEntity.java
  cakey-domain/src/main/java/com/cakey/common/JpaAuditingConfig.java
  cakey-domain/src/main/java/com/cakey/user/domain/.gitkeep
  cakey-domain/src/main/java/com/cakey/user/exception/UserDomainException.java
  cakey-domain/src/main/java/com/cakey/user/repository/.gitkeep
  cakey-domain/src/main/java/com/cakey/user/service/.gitkeep
  cakey-external/src/main/java/com/cakey/Main.java
  cakey-external/src/main/java/com/cakey/aws/.gitkeep
Labels: feat, setting, 성준

#8 [SETTING] 도메인 세팅 - #7
  cakey-domain/src/main/java/com/cakey/cake/domain/Cake.java
  cakey-domain/src/main/java/com/cakey/cake/domain/DayCategory.java
  cakey-domain/src/main/java/com/cakey/cakeimage/domain/CakeImages.java
  cakey-domain/src/main/java/com/cakey/cakelike/domain/CakeLikes.java
  cakey-domain/src/main/java/com/cakey/caketheme/domain/CakeTheme.java
  cakey-domain/src/main/java/com/cakey/caketheme/domain/ThemeName.java
  cakey-domain/src/main/java/com/cakey/operationtime/domain/StoreOperationTime.java
  cakey-domain/src/main/java/com/cakey/size/domain/Size.java
  cakey-domain/src/main/java/com/cakey/store/domain/Station.java
  cakey-domain/src/main/java/com/cakey/store/domain/Store.java
  cakey-domain/src/main/java/com/cakey/user/domain/.gitkeep
  cakey-domain/src/main/java/com/cakey/user/domain/SocialType.java
  cakey-domain/src/main/java/com/cakey/user/domain/User.java
  cakey-domain/src/main/java/com/cakey/user/domain/UserRole.java
Labels: setting, 성준

#12 [FEAT] 스토어 좌표 리스트 조회 api 구현 - #9
  cakey-api/src/main/java/com/cakey/controller/.gitkeep
  cakey-api/src/main/java/com/cakey/dto/.gitkeep
  cakey-api/src/main/java/com/cakey/exception/CakeyApiException.java
  cakey-api/src/main/java/com/cakey/exception/handler/GlobalExceptionHandler.java
  cakey-api/src/main/java/com/cakey/exception/user/.gitkeep
  cakey-api/src/main/java/com/cakey/facade/.gitkeep
  cakey-api/src/main/java/com/cakey/store/controller/StoreController.java
  cakey-api/src/main/java/com/cakey/store/dto/StoreCoordinate.java
  cakey-api/src/main/java/com/cakey/store/dto/StoreCoordinateListRes.java
  cakey-api/src/main/java/com/cakey/store/service/StoreService.java
  cakey-api/src/main/java/com/cakey/user/exception/UserApiException.java
  cakey-common/src/main/java/com/cakey/exception/CakeyException.java
  cakey-common/src/main/java/com/cakey/exception/UserBaseException.java
  cakey-domain/build.gradle
  cakey-domain/src/main/java/com/cakey/common/config/JpaAuditingConfig.java
  cakey-domain/src/main/java/com/cakey/common/config/QueryDSLConfig.java
  cakey-domain/src/main/java/com/cakey/common/exception/CakeyDomainException.java
  cakey-domain/src/main/java/com/cakey/common/exception/NotFoundException.java
  cakey-domain/src/main/java/com/cakey/store/domain/Station.java
  cakey-domain/src/main/java/com/cakey/store/domain/Store.java
  cakey-domain/src/main/java/com/cakey/store/dto/StoreCoordianteDto.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreFacade.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreRetriever.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepository.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepositoryCustom.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepositoryImpl.java
  cakey-domain/src/main/java/com/cakey/user/exception/UserDomainException.java
  cakey-domain/src/main/java/com/cakey/user/service/.gitkeep
Labels: feat, 성준

#18 [FEAT] 스토어 리스트 조회(인기순) API 구현 - #13
  cakey-api/src/main/java/com/cakey/store/controller/StoreController.java
  cakey-api/src/main/java/com/cakey/store/dto/StoreCoordinate.java
  cakey-api/src/main/java/com/cakey/store/dto/StoreInfo.java
  cakey-api/src/main/java/com/cakey/store/dto/StoreInfoListRes.java
  cakey-api/src/main/java/com/cakey/store/service/StoreService.java
  cakey-common/src/main/java/com/cakey/OrderBy.java
  cakey-domain/src/main/java/com/cakey/cake/domain/Cake.java
  cakey-domain/src/main/java/com/cakey/cake/dto/CakeMainImageDto.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeFacade.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeRetriever.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepository.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepositoryCustom.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepositoryCustomImpl.java
  cakey-domain/src/main/java/com/cakey/cakeimage/domain/CakeImages.java
  cakey-domain/src/main/java/com/cakey/common/BaseTimeEntity.java
  cakey-domain/src/main/java/com/cakey/store/domain/Station.java
  cakey-domain/src/main/java/com/cakey/store/domain/Store.java
  cakey-domain/src/main/java/com/cakey/store/dto/StoreInfoDto.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreFacade.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreRetriever.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepository.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepositoryCustom.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepositoryImpl.java
  cakey-domain/src/main/java/com/cakey/storelike/domain/StoreLike.java
Labels: feat, 성준

#20 [FEAT] 스토어 정보 리스트 조회(최신순) api 구현 - #19
  cakey-api/src/main/java/com/cakey/CakeyServerApplication.java
  cakey-api/src/main/java/com/cakey/common/auth/JwtTokenProvider.java
  cakey-api/src/main/java/com/cakey/common/auth/UserAuthentication.java
  cakey-api/src/main/java/com/cakey/common/resolver/user/UserIdResolver.java
  cakey-api/src/main/java/com/cakey/config/SecurityConfig.java
  cakey-api/src/main/java/com/cakey/store/controller/StoreController.java
  cakey-api/src/main/java/com/cakey/store/dto/StoreInfoListByLatest.java
  cakey-api/src/main/java/com/cakey/store/dto/StoreInfoListBylikesRes.java
  cakey-api/src/main/java/com/cakey/store/dto/StoreInfoListRes.java
  cakey-api/src/main/java/com/cakey/store/service/StoreService.java
  cakey-auth/build.gradle
  cakey-domain/src/main/java/com/cakey/store/facade/StoreFacade.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreRetriever.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepositoryCustom.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepositoryImpl.java
Labels: feat, 성준

#24 [FEAT] 사용자 이름 조회 API 구현 - #15
  cakey-api/src/main/java/com/cakey/user/controller/UserController.java
  cakey-api/src/main/java/com/cakey/user/dto/UserInfoRes.java
  cakey-api/src/main/java/com/cakey/user/exception/UserErrorCode.java
  cakey-api/src/main/java/com/cakey/user/service/UserService.java
  cakey-auth/src/main/java/com/cakey/client/dto/KakaoUserInfoRes.java
  cakey-auth/src/main/java/com/cakey/client/kakao/api/KakaoSocialService.java
  cakey-auth/src/main/java/com/cakey/client/kakao/api/SocialService.java
  cakey-domain/src/main/java/com/cakey/user/domain/User.java
  cakey-domain/src/main/java/com/cakey/user/dto/UserInfoDto.java
  cakey-domain/src/main/java/com/cakey/user/facade/UserFacade.java
  cakey-domain/src/main/java/com/cakey/user/facade/UserRetriever.java
  cakey-domain/src/main/java/com/cakey/user/repository/UserRepository.java
  cakey-domain/src/main/java/com/cakey/user/repository/UserRepositoryCustom.java
  cakey-domain/src/main/java/com/cakey/user/repository/UserRepositoryImpl.java
Labels: feat, 예린

#26 [FEAT] 찜한 스토어 조회(최신순) - #23
  cakey-api/src/main/java/com/cakey/store/dto/StoreInfoListBylikesRes.java
  cakey-api/src/main/java/com/cakey/store/service/StoreService.java
  cakey-api/src/main/java/com/cakey/storelikes/controller/StoreLikesController.java
  cakey-api/src/main/java/com/cakey/storelikes/dto/StoreLatestLikedByUser.java
  cakey-api/src/main/java/com/cakey/storelikes/service/StoreLikesService.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeFacade.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeRetriever.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepositoryCustom.java
  cakey-domain/src/main/java/com/cakey/store/dto/StoreInfoDto.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreFacade.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreRetriever.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepositoryCustom.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepositoryImpl.java
Labels: feat, 성준

#28 [FEAT] 스토어 카카오 오픈채팅 링크 조회 구현 - #25
  cakey-api/src/main/java/com/cakey/store/controller/StoreController.java
  cakey-api/src/main/java/com/cakey/store/dto/StoreKakaoLinkRes.java
  cakey-api/src/main/java/com/cakey/store/service/StoreService.java
  cakey-domain/src/main/java/com/cakey/store/dto/StoreKakaoLinkDto.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreFacade.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreRetriever.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepository.java
Labels: feat, 예린

#30 [FEAT] 스토어 상세 디자인 조회 구현 - #29
  cakey-api/src/main/java/com/cakey/store/controller/StoreController.java
  cakey-api/src/main/java/com/cakey/store/dto/StoreDetailAllDesignRes.java
  cakey-api/src/main/java/com/cakey/store/dto/StoreDetailDesign.java
  cakey-api/src/main/java/com/cakey/store/service/StoreService.java
  cakey-domain/src/main/java/com/cakey/cake/dto/CakeDesignDto.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeFacade.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeRetriever.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepository.java
  cakey-domain/src/main/java/com/cakey/cakelike/facade/CakeLikesFacade.java
  cakey-domain/src/main/java/com/cakey/cakelike/facade/CakeLikesRetriever.java
  cakey-domain/src/main/java/com/cakey/cakelike/repository/CakeLikesRepository.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepository.java
Labels: feat, 예린

#35 [FEAT] 찜한 스토어 조회(인기순) - #27
  cakey-api/src/main/java/com/cakey/store/controller/StoreController.java
  cakey-api/src/main/java/com/cakey/store/service/StoreService.java
  cakey-api/src/main/java/com/cakey/storelikes/controller/StoreLikesController.java
  cakey-api/src/main/java/com/cakey/storelikes/dto/StoreLatestLikedByUser.java
  cakey-api/src/main/java/com/cakey/storelikes/dto/StoreLatestLikedByUserRes.java
  cakey-api/src/main/java/com/cakey/storelikes/dto/StorePopularityLikedByUserRes.java
  cakey-api/src/main/java/com/cakey/storelikes/service/StoreLikesService.java
  cakey-domain/src/main/java/com/cakey/store/dto/StoreInfoDto.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreFacade.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreRetriever.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepositoryCustom.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepositoryImpl.java
  cakey-domain/src/main/java/com/cakey/storelike/StoreLikeRepository.java
  cakey-domain/src/main/java/com/cakey/storelike/facade/StoreLikeFacade.java
  cakey-domain/src/main/java/com/cakey/storelike/facade/StoreLikeRetriever.java
Labels: feat, 성준

#37 [FEAT] 해당 역 디자인 조회(최신순) - #36
  cakey-api/src/main/java/com/cakey/cake/controller/CakeController.java
  cakey-api/src/main/java/com/cakey/cake/dto/CakeInfo.java
  cakey-api/src/main/java/com/cakey/cake/dto/CakesByStationStoreRes.java
  cakey-api/src/main/java/com/cakey/cake/service/CakeService.java
  cakey-api/src/main/java/com/cakey/store/dto/StoreInfoListByLatest.java
  cakey-api/src/main/java/com/cakey/store/dto/StoreInfoListByLatestRes.java
  cakey-api/src/main/java/com/cakey/store/service/StoreService.java
  cakey-api/src/main/java/com/cakey/storelikes/service/StoreLikesService.java
  cakey-domain/src/main/java/com/cakey/cake/dto/CakeInfoDto.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeFacade.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeRetriever.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepository.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepositoryCustom.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepositoryCustomImpl.java
Labels: feat, 성준

#41 [FEAT] 해당역 디자인 조회(인기순) 구현- #38
  cakey-api/src/main/java/com/cakey/cake/controller/CakeController.java
  cakey-api/src/main/java/com/cakey/cake/dto/CakeInfo.java
  cakey-api/src/main/java/com/cakey/cake/dto/CakesByStationStoreRes.java
  cakey-api/src/main/java/com/cakey/cake/dto/CakesLatestByStationStoreRes.java
  cakey-api/src/main/java/com/cakey/cake/dto/CakesPopularByStationStoreRes.java
  cakey-api/src/main/java/com/cakey/cake/service/CakeService.java
  cakey-api/src/main/java/com/cakey/store/controller/StoreController.java
  cakey-api/src/main/java/com/cakey/store/dto/StoreInfoListByLatestRes.java
  cakey-api/src/main/java/com/cakey/store/dto/StoreInfoListBylikesRes.java
  cakey-api/src/main/java/com/cakey/store/service/StoreService.java
  cakey-api/src/main/java/com/cakey/storelikes/controller/StoreLikesController.java
  cakey-api/src/main/java/com/cakey/storelikes/dto/StoreLatestLikedByUserRes.java
  cakey-api/src/main/java/com/cakey/storelikes/dto/StorePopularityLikedByUserRes.java
  cakey-api/src/main/java/com/cakey/storelikes/service/StoreLikesService.java
  cakey-domain/src/main/java/com/cakey/cake/dto/CakeInfoDto.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeFacade.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeRetriever.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepositoryCustom.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepositoryCustomImpl.java
  cakey-domain/src/main/java/com/cakey/store/dto/StoreInfoDto.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreFacade.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreRetriever.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepositoryCustom.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepositoryImpl.java
Labels: feat, 성준

#44 [FEAT] 인기 케이크 조회 - #42
  cakey-api/src/main/java/com/cakey/cake/controller/CakeController.java
  cakey-api/src/main/java/com/cakey/cake/dto/CakeListByPopularityRes.java
  cakey-api/src/main/java/com/cakey/cake/service/CakeService.java
  cakey-domain/src/main/java/com/cakey/cake/dto/CakeByPopularityDto.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeFacade.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeRetriever.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepository.java
Labels: feat, 예린

#47 [FEAT] 찜한 디자인 조회(최신순) api - #45
  cakey-api/src/main/java/com/cakey/cakelikes/controller/CakeLikesController.java
  cakey-api/src/main/java/com/cakey/cakelikes/dto/CakeLikedLatestRes.java
  cakey-api/src/main/java/com/cakey/cakelikes/service/CakeLikesService.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeFacade.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeRetriever.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepositoryCustom.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepositoryCustomImpl.java
  cakey-domain/src/main/java/com/cakey/cakelike/facade/CakeLikesFacade.java
  cakey-domain/src/main/java/com/cakey/cakelike/facade/CakeLikesRetriever.java
  cakey-domain/src/main/java/com/cakey/cakelike/repository/CakeLikesRepository.java
Labels: feat, 성준

#49 [FEAT] 디자인 좋아요 하기 - #46
  cakey-api/src/main/java/com/cakey/cake/controller/CakeController.java
  cakey-api/src/main/java/com/cakey/cake/service/CakeService.java
  cakey-api/src/main/java/com/cakey/store/controller/StoreController.java
  cakey-api/src/main/java/com/cakey/store/service/StoreService.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeFacade.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeRetriever.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepository.java
  cakey-domain/src/main/java/com/cakey/cakelike/facade/CakeLikesFacade.java
  cakey-domain/src/main/java/com/cakey/cakelike/facade/CakeLikesRetriever.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreFacade.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreRetriever.java
Labels: feat, 예린

#54 [FEAT] 찜한 스토어 좌표 조회 - #53
  cakey-api/src/main/java/com/cakey/store/dto/StoreLikedCoordinateRes.java
  cakey-api/src/main/java/com/cakey/store/service/StoreService.java
  cakey-api/src/main/java/com/cakey/storelikes/controller/StoreLikesController.java
  cakey-api/src/main/java/com/cakey/storelikes/service/StoreLikesService.java
  cakey-domain/src/main/java/com/cakey/store/domain/Store.java
  cakey-domain/src/main/java/com/cakey/store/dto/StoreCoordianteDto.java
  cakey-domain/src/main/java/com/cakey/store/dto/StoreCoordinatesDto.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreFacade.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreRetriever.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepository.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepositoryCustom.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepositoryImpl.java
Labels: feat, 성준

#56 [FEAT] 선택 디자인 조회 - #55
  cakey-api/src/main/java/com/cakey/cake/controller/CakeController.java
  cakey-api/src/main/java/com/cakey/cake/dto/CakeSelectedInfo.java
  cakey-api/src/main/java/com/cakey/cake/dto/CakeSelectedRes.java
  cakey-api/src/main/java/com/cakey/cake/service/CakeService.java
  cakey-api/src/main/java/com/cakey/store/controller/StoreController.java
  cakey-domain/src/main/java/com/cakey/cake/dto/CakeSelectedDto.java
  cakey-domain/src/main/java/com/cakey/cake/dto/CakeSelectedInfoDto.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeFacade.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeRetriever.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepositoryCustom.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepositoryCustomImpl.java
  cakey-domain/src/main/java/com/cakey/store/dto/StoreBySelectedCakeDto.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreFacade.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreRetriever.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepositoryCustom.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepositoryImpl.java
Labels: feat, 성준

#60 [FEAT] 디자인 둘러보기 조회(인기순) - #59
  cakey-api/src/main/java/com/cakey/cake/controller/CakeController.java
  cakey-api/src/main/java/com/cakey/cake/service/CakeService.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeFacade.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeRetriever.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepositoryCustom.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepositoryCustomImpl.java
Labels: feat, 성준

#64 [FEAT] 찜한 스토어 디자인 조회(최신순) - #63
  cakey-api/src/main/java/com/cakey/cake/controller/CakeController.java
  cakey-api/src/main/java/com/cakey/cake/service/CakeService.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeFacade.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeRetriever.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepositoryCustom.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepositoryCustomImpl.java
Labels: feat, 성준

#68 [FIX] Response 변수명 수정 - #67
  cakey-api/src/main/java/com/cakey/cake/dto/CakeInfo.java
  cakey-api/src/main/java/com/cakey/cake/service/CakeService.java
  cakey-api/src/main/java/com/cakey/store/controller/StoreController.java
  cakey-api/src/main/java/com/cakey/store/service/StoreService.java
  cakey-domain/src/main/java/com/cakey/cake/dto/CakeByPopularityDto.java
  cakey-domain/src/main/java/com/cakey/store/dto/StoreByPopularityDto.java
Labels: 예린, fix

#73 [FEAT] 디자인 좋아요 취소 구현 - #71
  cakey-api/src/main/java/com/cakey/cakelikes/controller/CakeLikesController.java
  cakey-api/src/main/java/com/cakey/cakelikes/service/CakeLikesService.java
  cakey-domain/src/main/java/com/cakey/cakelike/facade/CakeLikesFacade.java
  cakey-domain/src/main/java/com/cakey/cakelike/facade/CakeLikesRemover.java
  cakey-domain/src/main/java/com/cakey/cakelike/facade/CakeLikesRetriever.java
  cakey-domain/src/main/java/com/cakey/cakelike/repository/CakeLikesRepository.java
Labels: feat, 예린

#74 [FEAT] 스토어 찜 하기 api - #65
  cakey-api/src/main/java/com/cakey/cake/controller/CakeController.java
  cakey-api/src/main/java/com/cakey/cake/service/CakeService.java
  cakey-api/src/main/java/com/cakey/cakelikes/controller/CakeLikesController.java
  cakey-api/src/main/java/com/cakey/cakelikes/service/CakeLikesService.java
  cakey-api/src/main/java/com/cakey/storelikes/controller/StoreLikesController.java
  cakey-api/src/main/java/com/cakey/storelikes/service/StoreLikesService.java
  cakey-domain/src/main/java/com/cakey/cakelike/facade/CakeLikesRetriever.java
  cakey-domain/src/main/java/com/cakey/storelike/facade/StoreLikeFacade.java
  cakey-domain/src/main/java/com/cakey/storelike/facade/StoreLikesSaver.java
  cakey-domain/src/main/java/com/cakey/storelike/repository/StoreLikeRepository.java
Labels: feat, 성준

#77 [FEAT] 스토어 찜 취소 api - #76
  cakey-api/src/main/java/com/cakey/storelikes/controller/StoreLikesController.java
  cakey-api/src/main/java/com/cakey/storelikes/service/StoreLikesService.java
  cakey-domain/src/main/java/com/cakey/storelike/facade/StoreLikeFacade.java
  cakey-domain/src/main/java/com/cakey/storelike/facade/StoreLikeRetriever.java
  cakey-domain/src/main/java/com/cakey/storelike/facade/StoreLikesRemover.java
  cakey-domain/src/main/java/com/cakey/storelike/repository/StoreLikeRepository.java
Labels: feat, 성준

#79 [FEAT] 선택 스토어 조회 api - #78
  cakey-api/src/main/java/com/cakey/store/controller/StoreController.java
  cakey-api/src/main/java/com/cakey/store/dto/StoreSelectedRes.java
  cakey-api/src/main/java/com/cakey/store/service/StoreService.java
  cakey-domain/src/main/java/com/cakey/store/dto/StoreSelectedDto.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreFacade.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreRetriever.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepositoryCustom.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepositoryImpl.java
Labels: feat, 성준

#81 [FEAT] caffeine cache 적용 및 로그인 기능 구현 수정 - #70
  cakey-api/build.gradle
  cakey-api/src/main/java/com/cakey/common/auth/CustomAccessDeniedHandler.java
  cakey-api/src/main/java/com/cakey/common/auth/CustomJwtAuthenticationEntryPoint.java
  cakey-api/src/main/java/com/cakey/common/auth/JwtTokenProvider.java
  cakey-api/src/main/java/com/cakey/common/auth/UserAuthentication.java
  cakey-api/src/main/java/com/cakey/common/auth/filter/CustomAuthenticationFilter.java
  cakey-api/src/main/java/com/cakey/common/auth/filter/JwtAuthenticationFilter.java
  cakey-api/src/main/java/com/cakey/common/filter/OptionalAuthenticationFilter.java
  cakey-api/src/main/java/com/cakey/common/filter/RequiredAuthenticationFilter.java
  cakey-api/src/main/java/com/cakey/common/resolver/user/UserIdResolver.java
  cakey-api/src/main/java/com/cakey/config/CacheConfig.java
  cakey-api/src/main/java/com/cakey/config/RedisConfig.java
  cakey-api/src/main/java/com/cakey/config/SecurityConfig.java
  cakey-api/src/main/java/com/cakey/config/WebConfig.java
  cakey-api/src/main/java/com/cakey/user/controller/UserController.java
  cakey-api/src/main/java/com/cakey/user/dto/.gitkeep
  cakey-api/src/main/java/com/cakey/user/service/UserService.java
  cakey-auth/src/main/java/com/cakey/client/config/FeignConfig.java
  cakey-auth/src/main/java/com/cakey/client/dto/KakaoUserInfoDto.java
  cakey-auth/src/main/java/com/cakey/client/kakao/api/KakaoApiClient.java
  cakey-auth/src/main/java/com/cakey/client/kakao/api/KakaoSocialService.java
  cakey-auth/src/main/java/com/cakey/client/kakao/api/SocialService.java
  cakey-auth/src/main/java/com/cakey/client/kakao/api/dto/KakaoAccount.java
  cakey-auth/src/main/java/com/cakey/client/kakao/api/dto/KakaoUserDto.java
  cakey-auth/src/main/java/com/cakey/client/kakao/api/dto/UserCreateDto.java
  cakey-auth/src/main/java/com/cakey/jwt/auth/CustomAccessDeniedHandler.java
  cakey-auth/src/main/java/com/cakey/jwt/auth/CustomJwtAuthenticationEntryPoint.java
  cakey-auth/src/main/java/com/cakey/jwt/auth/JwtGenerator.java
  cakey-auth/src/main/java/com/cakey/jwt/auth/JwtProvider.java
  cakey-auth/src/main/java/com/cakey/jwt/auth/JwtValidationType.java
  cakey-auth/src/main/java/com/cakey/jwt/auth/UserAuthentication.java
  cakey-auth/src/main/java/com/cakey/jwt/domain/Token.java
  cakey-auth/src/main/java/com/cakey/jwt/repository/TokenRepository.java
  cakey-auth/src/main/java/com/cakey/jwt/service/TokenService.java
  cakey-domain/src/main/java/com/cakey/user/domain/User.java
  cakey-domain/src/main/java/com/cakey/user/dto/LoginSuccessRes.java
  cakey-domain/src/main/java/com/cakey/user/facade/UserCreator.java
  cakey-domain/src/main/java/com/cakey/user/facade/UserFacade.java
  cakey-domain/src/main/java/com/cakey/user/facade/UserRetriever.java
  cakey-domain/src/main/java/com/cakey/user/repository/UserRepository.java
  cakey-domain/src/main/java/com/cakey/user/repository/UserRepositoryImpl.java
Labels: feat, 예린

#84 [FEAT] arguments resolver - userid 적용 - #83
  cakey-api/src/main/java/com/cakey/cake/controller/CakeController.java
  cakey-api/src/main/java/com/cakey/cakelikes/controller/CakeLikesController.java
  cakey-api/src/main/java/com/cakey/common/resolver/user/UserIdResolver.java
  cakey-api/src/main/java/com/cakey/config/SecurityConfig.java
  cakey-api/src/main/java/com/cakey/store/controller/StoreController.java
  cakey-api/src/main/java/com/cakey/storelikes/controller/StoreLikesController.java
  cakey-api/src/main/java/com/cakey/user/controller/UserController.java
Labels: feat, 성준

#88 [fix] 이슈해결 - #87
  cakey-api/src/main/java/com/cakey/config/SecurityConfig.java
  cakey-api/src/main/java/com/cakey/exception/handler/GlobalExceptionHandler.java
  cakey-auth/src/main/java/com/cakey/client/kakao/api/KakaoAuthApiClient.java
  cakey-auth/src/main/java/com/cakey/client/kakao/api/KakaoSocialService.java
  cakey-auth/src/main/java/com/cakey/client/kakao/api/dto/KakaoAccessTokenRes.java
Labels: 성준, fix

#90 [FIX] 인기케이크 조회 api url 수정 - #89
  cakey-api/src/main/java/com/cakey/cake/controller/CakeController.java
  cakey-api/src/main/java/com/cakey/store/controller/StoreController.java
Labels: 성준, fix

#92 [CHORE] 로그인 dto 변경 [#91]
  cakey-api/src/main/java/com/cakey/user/controller/UserController.java
  cakey-api/src/main/java/com/cakey/user/service/UserService.java
Labels: feat, 성준

#94 [CHORE] 로그인 redirect url 요청값 추가 #93
  cakey-api/src/main/java/com/cakey/user/service/UserService.java
  cakey-auth/src/main/java/com/cakey/client/dto/LoginReq.java
  cakey-auth/src/main/java/com/cakey/client/kakao/api/KakaoSocialService.java
Labels: feat, 성준

#96 [FIX] res.cookie 이슈 - #95
  cakey-api/src/main/java/com/cakey/user/controller/UserController.java
  cakey-api/src/main/java/com/cakey/user/service/UserService.java
  cakey-auth/src/main/java/com/cakey/jwt/auth/JwtGenerator.java
Labels: 성준, fix

#103 [FIX] 필드명변경 #102
  cakey-api/src/main/java/com/cakey/store/dto/AllStationRes.java
Labels: 성준, fix

#105 [FIX] 스토어 좌표 리스트 예외 추가 - #104
  cakey-api/src/main/java/com/cakey/store/service/StoreService.java
Labels: feat, 성준

#107 [FEAT] cutsom Exception handle - #106
  cakey-api/src/main/java/com/cakey/cake/exception/CakeApiBaseException.java
  cakey-api/src/main/java/com/cakey/common/response/ApiResponseUtil.java
  cakey-api/src/main/java/com/cakey/exception/handler/GlobalExceptionHandler.java
  cakey-api/src/main/java/com/cakey/store/exception/StoreApiBaseException.java
  cakey-api/src/main/java/com/cakey/user/exception/UserApiBaseException.java
Labels: feat, 성준

#111 [FIX] 커스텀 filter url 추가- #109
  cakey-api/src/main/java/com/cakey/cake/controller/CakeController.java
  cakey-api/src/main/java/com/cakey/config/FilterConfig.java
  cakey-api/src/main/java/com/cakey/store/controller/StoreController.java
  cakey-api/src/main/java/com/cakey/user/controller/UserController.java
Labels: 성준, fix

#113 [FIX] 쿠키 사용 이슈 #112
  cakey-api/src/main/java/com/cakey/common/filter/OptionalAuthenticationFilter.java
  cakey-api/src/main/java/com/cakey/common/filter/RequiredAuthenticationFilter.java
  cakey-api/src/main/java/com/cakey/config/FilterConfig.java
Labels: 성준, fix

#119 [FEAT] exception 메세지 구체화 #118
  cakey-api/build.gradle
  cakey-api/src/main/java/com/cakey/cake/controller/CakeController.java
  cakey-api/src/main/java/com/cakey/cake/exception/CakeErrorCode.java
  cakey-api/src/main/java/com/cakey/cake/service/CakeService.java
  cakey-api/src/main/java/com/cakey/cakelikes/service/CakeLikesService.java
  cakey-api/src/main/java/com/cakey/common/filter/OptionalAuthenticationFilter.java
  cakey-api/src/main/java/com/cakey/config/FilterConfig.java
  cakey-api/src/main/java/com/cakey/exception/handler/GlobalExceptionHandler.java
  cakey-api/src/main/java/com/cakey/store/exception/StoreConflictBaseException.java
  cakey-api/src/main/java/com/cakey/store/service/StoreService.java
  cakey-api/src/main/java/com/cakey/storelikes/controller/StoreLikesController.java
  cakey-api/src/main/java/com/cakey/storelikes/service/StoreLikesService.java
  cakey-api/src/main/java/com/cakey/user/exception/UserErrorCode.java
  cakey-api/src/main/java/com/cakey/user/service/UserService.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeFacade.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeRetriever.java
  cakey-domain/src/main/java/com/cakey/cakelike/facade/CakeLikesFacade.java
  cakey-domain/src/main/java/com/cakey/cakelike/facade/CakeLikesRetriever.java
  cakey-domain/src/main/java/com/cakey/cakelike/repository/CakeLikesRepository.java
  cakey-domain/src/main/java/com/cakey/operationtime/facade/StoreOperationTimeRetriever.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreRetriever.java
Labels: feat, 성준

#121 [FEAT] valid 적용 및 운영시간 포매터 수정 - #120
  cakey-api/src/main/java/com/cakey/store/service/StoreService.java
Labels: feat, 성준

#126 [FIX] 스토어 정보 리스트 조회(인기순) 수정 #125
  cakey-api/src/main/java/com/cakey/store/controller/StoreController.java
  cakey-domain/src/main/java/com/cakey/store/repository/StoreRepositoryImpl.java
Labels: 성준, fix

#131 [FIX] 찜한 스토어의 디자인 인기순 조회 #130
  cakey-api/src/main/java/com/cakey/storelikes/dto/StorePopularityLikedByUserRes.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepositoryCustomImpl.java
  cakey-domain/src/main/java/com/cakey/common/exception/BadRequestBaseException.java
Labels: 성준, fix

#133 [FIX] 케이크 인기순 조회 groupby #132
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepositoryCustomImpl.java
Labels: 성준, fix

#135 [FEAT] Valid 추가 - #134
  build.gradle
  cakey-api/build.gradle
  cakey-api/src/main/java/com/cakey/cake/controller/CakeController.java
  cakey-api/src/main/java/com/cakey/cake/exception/CakeyApiBaseException.java
  cakey-api/src/main/java/com/cakey/cake/exception/CakeyBadRequestBaseException.java
  cakey-api/src/main/java/com/cakey/cake/exception/CakeyConflictBaseException.java
  cakey-api/src/main/java/com/cakey/cake/exception/CakeyForbiddenBaseException.java
  cakey-api/src/main/java/com/cakey/cake/exception/CakeyNotFoundException.java
  cakey-api/src/main/java/com/cakey/cake/service/CakeService.java
  cakey-api/src/main/java/com/cakey/cakelikes/controller/CakeLikesController.java
  cakey-api/src/main/java/com/cakey/cakelikes/service/CakeLikesService.java
  cakey-api/src/main/java/com/cakey/common/filter/OptionalAuthenticationFilter.java
  cakey-api/src/main/java/com/cakey/config/FilterConfig.java
  cakey-api/src/main/java/com/cakey/exception/handler/GlobalExceptionHandler.java
  cakey-api/src/main/java/com/cakey/store/controller/StoreController.java
  cakey-api/src/main/java/com/cakey/store/exception/StoreApiBaseException.java
  cakey-api/src/main/java/com/cakey/store/service/StoreService.java
  cakey-api/src/main/java/com/cakey/storelikes/controller/StoreLikesController.java
  cakey-api/src/main/java/com/cakey/storelikes/service/StoreLikesService.java
  cakey-api/src/main/java/com/cakey/user/controller/UserController.java
  cakey-api/src/main/java/com/cakey/user/exception/UserApiBaseException.java
  cakey-api/src/main/java/com/cakey/user/service/UserService.java
  cakey-api/src/main/java/com/cakey/validate/EnumValue.java
  cakey-api/src/main/java/com/cakey/validate/ValueOfEnumValidator.java
  cakey-auth/src/main/java/com/cakey/client/dto/LoginReq.java
  cakey-auth/src/main/java/com/cakey/exception/AuthBaseException.java
  cakey-common/src/main/java/com/cakey/exception/CakeBaseException.java
  cakey-common/src/main/java/com/cakey/exception/CakeyBaseException.java
  cakey-common/src/main/java/com/cakey/rescode/ErrorBaseCode.java
  cakey-domain/src/main/java/com/cakey/cake/facade/CakeFacade.java
  cakey-domain/src/main/java/com/cakey/common/exception/BadRequestBaseException.java
  cakey-domain/src/main/java/com/cakey/common/exception/CakeDomainBaseException.java
  cakey-domain/src/main/java/com/cakey/common/exception/CakeyDomainBaseException.java
  cakey-domain/src/main/java/com/cakey/common/exception/NotFoundBaseException.java
  cakey-domain/src/main/java/com/cakey/size/facade/SizeFacade.java
  cakey-domain/src/main/java/com/cakey/store/facade/StoreFacade.java
  cakey-domain/src/main/java/com/cakey/user/exception/UserDomainBaseException.java
  cakey-domain/src/main/java/com/cakey/user/facade/UserFacade.java
Labels: feat, 성준

#137 [FIX] enum valid 수정 #136
  cakey-api/build.gradle
  cakey-api/src/main/java/com/cakey/cake/controller/CakeController.java
  cakey-api/src/main/java/com/cakey/cakelikes/controller/CakeLikesController.java
  cakey-api/src/main/java/com/cakey/common/filter/RequiredAuthenticationFilter.java
  cakey-api/src/main/java/com/cakey/exception/handler/GlobalExceptionHandler.java
  cakey-api/src/main/java/com/cakey/store/controller/StoreController.java
  cakey-api/src/main/java/com/cakey/user/controller/UserController.java
  cakey-api/src/main/java/com/cakey/validate/EnumValue.java
  cakey-api/src/main/java/com/cakey/validate/ValueOfEnumValidator.java
  cakey-api/src/main/resources/logback-spring.xml
  cakey-auth/src/main/java/com/cakey/client/dto/LoginReq.java
  cakey-domain/src/main/java/com/cakey/store/domain/Station.java
Labels: 성준, fix

#139 [FEAT] 필터 예외 처리 추가 - #138
  cakey-api/src/main/java/com/cakey/common/Constant.java
  cakey-api/src/main/java/com/cakey/common/filter/RequiredAuthenticationFilter.java
  cakey-api/src/main/java/com/cakey/user/exception/UserErrorCode.java
  cakey-api/src/main/java/com/cakey/user/service/UserService.java
  cakey-auth/src/main/java/com/cakey/jwt/auth/JwtGenerator.java
  cakey-auth/src/main/java/com/cakey/jwt/auth/JwtProperties.java
  cakey-common/src/main/java/com/cakey/rescode/ErrorBaseCode.java
Labels: feat, 성준

#149 [SETTING] 도메인 변경 - #148
  cakey-api/src/main/java/com/cakey/store/service/StoreService.java
  cakey-domain/src/main/java/com/cakey/operationtime/domain/StoreOperationTime.java
  cakey-domain/src/main/java/com/cakey/operationtime/dto/StoreOperationTimeDto.java
  cakey-domain/src/main/java/com/cakey/store/domain/Store.java
Labels: feat, 성준

#153 [FIX] 개수 수정 #152
  cakey-api/src/main/java/com/cakey/cake/service/CakeService.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepository.java
  cakey-domain/src/main/java/com/cakey/cake/repository/CakeRepositoryCustomImpl.java
Labels: 성준, fix

#156 [FEAT] jwt
  cakey-api/src/main/java/com/cakey/common/filter/OptionalAuthenticationFilter.java
  cakey-api/src/main/java/com/cakey/common/filter/RequiredAuthenticationFilter.java
  cakey-auth/src/main/java/com/cakey/jwt/auth/JwtProvider.java
Labels: feat, 성준

#157 [FEAT] 캐시 테스트 코드 #147
  cakey-api/build.gradle
  cakey-api/src/main/java/com/cakey/cake/controller/CakeController.java
  cakey-api/src/main/java/com/cakey/common/filter/RequiredAuthenticationFilter.java
  cakey-api/src/main/java/com/cakey/config/CacheConfig.java
  cakey-api/src/main/java/com/cakey/store/controller/StoreController.java
  cakey-api/src/main/java/com/cakey/user/service/UserService.java
  cakey-api/src/main/resources/logback-spring.xml
  cakey-auth/build.gradle
  cakey-auth/src/main/java/com/cakey/jwt/CacheConfig.java
  cakey-auth/src/main/java/com/cakey/jwt/auth/JwtProvider.java
  cakey-auth/src/test/java/com/cakey/TestConfiguration.java
  cakey-auth/src/test/java/com/cakey/jwt/auth/JwtGeneratorTest.java
Labels: feat, 성준

#161 [FIX] 무악재역 좌표 수정 - #160
  cakey-domain/src/main/java/com/cakey/store/domain/Station.java
Labels: 예린, fix
